language: node_js
node_js:
- node
- '6'
- '4'
addons:
  code_climate:
    repo_token: c5f0a0925326006c8c9a905a7019724c8339b8a3d346c059ed6f4a1f0e4bbf21
notifications:
  email: false
  slack:
    rooms:
      secure: h0cufSToTDwDuP1t/nzKidFoa2P4rgEBA1H4oISUOdnbmA33Mm1iuC49uyNMMci4Mt1ximDbZF/O/xaQjwPYea24xGGQ+TI2WfsCw8f6Jp9w1Md0qRbDIrB/TLQ8h2ij5oHNlFl4nps8nh0ffa6PE+mylbmMcJfmJGjiGrL/wIBzRxsVAisWsFNjkkAfc9VLdZ1b1ridUiwdVANY0OPBZMrMDvlJffRi8wKK3QnizFsvWbT2nVycKn0Ao5d72XTv//RMaAhNGaLny0mR8vRJ8eyvDmRA8zM+ekmIk83BzyqNBY8y6xrwrU9sSfW3kFcm5zPdjI841o5MM0judo4yGf4z08oryOTm99a05dhfIlt3Vv0OmEy38AS9pxJucq0QRyVsgY0MHRw+WKECWC5H9/OPEWEHNfWoJVr0V+sPoa734JerzzKPDOwTEJ/ERx0Mj75zxKpeyRpIZ3roptfakRfjtAn+l1RjGJi7DRc6eIVuHP2tbmoiwpCZcnK+3IMZPWNsCW6fauiYO+AnuuyZLeIFbHF8Bt/tX7h+8iFQJ6OM/Wy/qPZ2RbZm5JQ7bUdzIem+ATj7dEBtAAcfyIYYrow5TYo6CRSSk4tgqg0mv/ejcHubj46e8SBQ3Hd6g/D8tgA/AXPHmsHPJ++pOS8Ce4ouyn6rC1y9LzgUWJayarA=
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
sudo: false
